name: CI Pipeline - Build & Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'Dockerfile'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. checkout of code 
        uses: actions/checkout@v4

      - name: 2. GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # <-- ΑΛΛΑΓΗ ΕΔΩ

      - name: 3. image built
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/dhmhtrhsgkantiafikas/asgi-server-in-kubernetes-enviroment:${{ github.sha }}
            ghcr.io/dhmhtrhsgkantiafikas/asgi-server-in-kubernetes-enviroment:latest
